#!/usr/bin/python3

import sys
import time


def factorize(number):
    factors = []
    i = 2
    while i * i <= number:
        if number % i:
            i += 1
        else:
            number //= i
            factors.append(i)
    if number > 1:
        factors.append(number)
    return factors


def factorize_numbers(file_path):
    with open(file_path, 'r') as file:
        numbers = file.read().splitlines()

    for number in numbers:
        number = int(number)
        factors = factorize(number)
        factors_str = '*'.join(map(str, factors))
        print(f"{number}={factors_str}")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        sys.exit(1)

    file_path = sys.argv[1]

    start_time = time.time()
    factorize_numbers(file_path)
    end_time = time.time()

    execution_time = end_time - start_time
    print(f"\nExecution time: {execution_time:.3f} seconds")
