#!/usr/bin/python3
from factors_functions import print_factors
import time

if __name__ == '__main__':
    start_time = time.time()
    print_factors()
    end_time = time.time()
    execution_time = end_time - start_time
    print("Execution time:", execution_time, "seconds")
